### PR TITLE
LIME-392:  Fixed destructure email error

### LINKED ISSUE #392: BUG: Error when logged in user tries to refresh page
### Describe your issue

When logged in user tries to refresh page, error is displayed instead of page

### Steps to reproduce

1. Login with valid credentials on https://live-in-motion-everyday.com/
2. Being on overview page, try to refresh it

### What was the actual result?

TypeError is displayed on the page

### What was the expected result?

Content is displayed on the page

### Put here any screenshots or videos (optional)

image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

### PR DESCRIPTION
**Pull request by jhladkov**
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/74872088/4831689d-0c30-4131-b11a-63e05326a4fb

### CODE REVIEW

File: frontend/src/bundles/common/components/protected-route/protected-route.tsx [hunk 1]
```diff
@@ -8,16 +8,20 @@ type ProtectedRouteProperties = {
...
-        isRefreshing: auth.isRefreshing,
-        userAuthenticated: auth.user,
-    }));
+    const { isRefreshing, userAuthenticated, dataStatus } = useAppSelector(
+        ({ auth }) => ({
+            isRefreshing: auth.isRefreshing,
+            userAuthenticated: auth.user,
+            dataStatus: auth.dataStatus,
+        }),
+    );
```
Comment (nikita-remeslov) [inline frontend/src/bundles/common/components/protected-route/protected-route.tsx]:
```suggestion
    const { isRefreshing, userAuthenticated, dataStatus } = useAppSelector(
        ({ auth }) => auth
    );
```

File: frontend/src/app/app.tsx [hunk 2]
```diff
@@ -9,17 +9,16 @@ import {
...
 } from '~/bundles/common/hooks/hooks.js';
 import { storage, StorageKey } from '~/framework/storage/storage.js';
 
 const App: React.FC = () => {
-    const [isRefreshing, setIsRefreshing] = useState(true);
     const dispatch = useAppDispatch();
     const navigate = useNavigate();
 
-    const { redirectPath } = useAppSelector(({ app }) => ({
+    const { redirectPath, isRefreshing } = useAppSelector(({ app, auth }) => ({
```
Comment (nikita-remeslov) [inline frontend/src/app/app.tsx]: we should use 2 selectors

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

**Review by nikita-remeslov — APPROVED** [review]
