### PR TITLE
LIME-428: avatar on user info card chat

### LINKED ISSUE #428: BUG: The avatar is not displayed on the User Info card on the Chat page
### Describe your issue

The avatar is not displayed on the User Info card on the Chat page

### Steps to reproduce

1. Go to the [https://live-in-motion-everyday.com/chats/1](https://live-in-motion-everyday.com/chats/1)
2. Click on the icon of the user at the top of a chat page
3. Pay attention to the avatar displayed

### What was the actual result?

The avatar is not displayed on the User Info card on the Chat page

### What was the expected result?

The avatar is displayed on the User Info card on the Chat page

### Put here any screenshots or videos (optional)

Image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by DavidCharif**
image
chat-image-card

### CODE REVIEW

File: frontend/src/bundles/common/components/user-info-card/user-info-card.tsx [hunk 1]
```diff
@@ -48,11 +49,7 @@ const UserInfoCard: React.FC<Properties> = ({
                         {name}
                     </p>
                 </div>
-                <img
-                    src={image}
-                    alt={name}
-                    className="h-44 w-44 overflow-hidden rounded-full object-cover"
-                />
+                <Avatar size="xl" email={image ? '' : name} avatarUrl={image} />
```
Comment (stpalamar) [inline frontend/src/bundles/common/components/user-info-card/user-info-card.tsx]:
```suggestion
                <Avatar size="xl" email={name} avatarUrl={image} />
```
You can pass just name because Avatar have this condition, if there is no image, name will be used for displaying.

**Review by valery-chumak — APPROVED** [review]

**Review by SergiiTernytskyi — APPROVED** [review]

**Review by stpalamar — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
