### PR TITLE
LIME-69: Add Profile Settings

### LINKED ISSUE #69: Add Profile Settings screen
**SPECS from QA Team**

Users can create and manage their profiles (Full Name, Nickname, Date of birth, Weight, Height, Sex). Include personal details, fitness goals, and preferences.

**1.** **Personal Information tab** (opened by default when user navigates from avatar menu icon in header)  should contain: 

**Avatar photo** 
- may be uploaded from the user’s device in PNG and JPEG format
- max size 20 MB
- may be cropped and zoomed manually 

**Field “Full Name”:**
- Should have minlength 2 characters and maxlength 60. 
- Unicode symbols - Letters (upper- and lowercase, latin and non-Latin), special characters, spaces, emoji are allowed.
- Contains placeholder John Doe
- Spaces before and after text should be cropped

**Field “Nickname”:**
- Should have minlength 2 characters and maxlength 30. 
- Unicode symbols - letters (upper- and lowercase, latin and non-Latin), special characters, spaces, emoji are allowed.
- Contains placeholder MyNickname2024
- Spaces before and after text should be cropped

**Field “Date of birth”:**
- Date can be entered manually or picked up from the Calendar (absent in design!!!)
- Format of date is DD/MM/YYYY, only past valid dates. 
- User should be prevented from entering the wrong date format - e.g. by using input masking.
- Field accepts numbers digits (0-9), any other characters aren’t accepted.
- Contains placeholder, showing format of date

**Field “Weight”:**
- Should have minlength 2 characters and maxlength 20.
- Digits (0-9), uppercase and lowercase Latin letters (A-Z, a-z), middle-placed comma, middle-placed dot, middle-placed space are allowed.
- Contains placeholder “0 kg” 
- Spaces before and after text should be cropped

**Field “Height”:**
- Should have minlength 2 characters and maxlength 20.
- Digits (0-9), uppercase and lowercase Latin letters (A-Z, a-z), middle- placed comma, middle-placed dot, middle-placed space are allowed.
- Contains placeholder “0 sm” 
-  Spaces before and after text should be cropped

**СOMMENT: All fields are optional for now but smth will be changed**

**Input “Male/Femail/Prefer not to say”:**  (last option absent in design)!!!
- Only one option can be selected

**Save button** (absent in design)!!!
- Should be disabled with empty mandatory fields
- Should be disabled after negative validation 

**Cancel button**  (absent in design)!!!
- Should be disabled if no changes were made
- Cancels all unsaved changes

**User should be prevented from leaving page without saving changes**: e.g. with pop-up asking “Do you want to save changes before leaving?” and buttons “Save” and “Discard changes”. If the uses closes pop-up without confirmation of saving or discarding, page is displayed with unsaved changes.

**Error messages**
- displayed under field with error value
- for empty mandatory field - Please fill out this field
- for invalid length or format for Full name, Nickname, Weight, Height - Please enter valid data
- for invalid calendar date - Please enter a valid past date in DD/MM/YYYY format

2. User should be redirected to the Goals page after clicking **Fitness Goals** tab link.

3. User should be able to add **Preferences**, searching for them as tags

Preferences are chosen among Activities: Running, Walking, Cycling (will be added).

Preferences page may contain:

- search field with a title Choose your preferences and placeholder Find an Activity
- area of added tags

Field accepts up to  50 characters - letters, digits, special characters. 
Spaces at the beginning of the input should be trimmed

Search should start automatically after entering 2 characters. User should be provided autocomplete menu with results, that include keyword value.

User should be able to choose one of the search results. Chosen value is added as a tag. 

User should be able to remove added preference in one click

User should be able to remove all preferences in one click and to make bulk choice for removing

Image

### PR DESCRIPTION
**Pull request by valery-chumak**

### CODE REVIEW

File: frontend/src/bundles/common/components/radio-card/radio-card.tsx
Comment (stpalamar) [inline frontend/src/bundles/common/components/radio-card/radio-card.tsx:1]: Can you provide some screenshots?

Also I don't understand why we need **RadioCard** component. We have already **Radio** component. You can add radio options for field "gender" like this.
image
If you need clickable label, I noticed one bug, you should change in **Radio** component label attribute to `htmlFor={id}` and this id should be unique for each radio like on screenshot

Comment (valery-chumak) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx:1]: I created a RadioCard because I have different styles for it than it was in Radio component. I need to use styles.module.css for putting styles over label when the input is checked and I can not do it directly in className property using tailwind, because the label does not have the checked property. So, if I apply those styles for our default Radio component it will override styles for it. Right now when the Radio is checked it makes label backround yellow and we don't need that for default Radio.

Comment (valery-chumak) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx:1]: Снимок экрана 2024-02-22 160334

Comment (valery-chumak) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx:1]: image
Tried the solution which you recommended, but it didn't work 😔

Comment (valery-chumak) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx:1]: @stpalamar Thanks for noticing the bug, now it works fine!

File: backend/src/bundles/users/user.repository.ts [hunk 1]
```diff
@@ -94,8 +96,40 @@ class UserRepository implements Repository {
...
+        userId: number,
+        updatedUserDetails: Partial<UserDetailsModel>,
+    ): Promise<UserEntity> {
+        const trx = await this.userModel.startTransaction();
+
+        try {
+            const user = await this.userModel.query(trx).findById(userId);
+
+            if (!user) {
+                throw new Error('User not found');
```
Comment (anton-otroshchenko) [inline backend/src/bundles/users/user.repository.ts]: Please create a constant for this error message if we don't have one already

File: backend/src/bundles/users/user.service.ts [hunk 2]
```diff
@@ -46,10 +48,43 @@ class UserService implements Service {
...
+                return updatedUser.toObject() as UserAuthResponseDto;
+            } else {
+                throw new Error('User not found');
+            }
+        } catch (error) {
+            throw new Error(`Error occured ${error}`);
+        }
+    }
+    private shouldUpdateProperty(value: unknown): boolean {
+        return value !== null && value !== '';
```
Comment (anton-otroshchenko) [inline backend/src/bundles/users/user.service.ts]:
```suggestion
        return value;
```
will this work?

File: frontend/src/bundles/auth/store/actions.ts [hunk 3]
```diff
@@ -30,4 +33,15 @@ const signIn = createAsyncThunk<
...
 
-export { signIn, signUp };
+const updateUser = createAsyncThunk<
+    UserAuthResponseDto,
+    UserUpdateProfileRequestDto,
+    AsyncThunkConfig
+>(`${sliceName}/update-user`, async (updateUserPayload, { extra }) => {
+    const { userApi } = extra;
+    const { id: userId } = updateUserPayload;
+    const userIdAsString: string = userId === null ? '' : userId.toString();
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/auth/store/actions.ts]:
```suggestion
    const userIdAsString: string = !userId ? '' : userId.toString();
```

File: frontend/src/bundles/common/components/radio-card/radio-card.tsx [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+
+import styles from './styles.module.css';
+
+type Properties<T extends FieldValues> = {
+    name: FieldPath<T>;
+    id: string;
+    label: string;
+    value: string;
+    control: Control<T>;
+    checked?: boolean;
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/common/components/radio-card/radio-card.tsx]: I guess we don't use this property in this component

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 5]
```diff
@@ -0,0 +1,208 @@
...
+
+import { DEFAULT_UPDATE_PROFILE_PAYLOAD } from './constants/constants.js';
+
+type Properties = {
+    onSubmit: (payload: UserUpdateProfileRequestDto) => void;
+    isLoading: boolean;
+};
+
+const extractNumbers = (value: string | undefined | null): string => {
+    return (value || '').trim().replaceAll(/\D/g, '');
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]:
```suggestion
    return (value ?? '').trim().replaceAll(/\D/g, '');
```

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 6]
```diff
@@ -0,0 +1,208 @@
...
+            mode: 'onBlur',
+            shouldUnregister: false,
+        });
+
+    // const handleUpdateFileButtonClick = (): void => {
+    //     const inputElement = document.querySelector(
+    //         '#avatarInput',
+    //     ) as HTMLInputElement;
+    //     inputElement?.click();
+    // };
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: do we need these comments?

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 7]
```diff
@@ -0,0 +1,208 @@
...
+    return (
+        <div className="bg-lm-black-200 w-[874px] px-12 pl-[52px] pr-[78px] pt-[48px]">
+            <div className="flex items-center pb-[47px]">
+                <Avatar size="lg" />
+
+                <input
+                    id="avatarInput"
+                    type="file"
+                    accept="image/jpeg, image/png"
+                    // onChange={handleAvatarChange}
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: and also this

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 8]
```diff
@@ -0,0 +1,208 @@
...
+                    className="hidden"
+                />
+                <Button
+                    className="ml-[13px] h-[38px] w-[115px] rounded-[20px]"
+                    type="submit"
+                    label="Update file"
+                    variant={ButtonVariant.SECONDARY}
+                    size={ButtonSize.SMALL}
+                    // onClick={handleUpdateFileButtonClick}
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: and this

**Review by anton-otroshchenko — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/common/components/radio-card/radio-card.tsx (hunk 4 above)
Comment (valery-chumak) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx]: @anton-otroshchenko Which one?

File: backend/src/bundles/users/user.service.ts (hunk 2 above)
Comment (valery-chumak) [reply backend/src/bundles/users/user.service.ts]: Yes) But there is an error that type 'unknown' is not assignable to type 'boolean'. So, I can make it like this `return Boolean(value)`

File: frontend/src/bundles/common/components/radio-card/radio-card.tsx
Comment (stpalamar) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx:1]: I have combined your component RadioCard with existing Radio and created RadioType for two variants. Try it
Also I just took your styles, so pay attention that you shouldn't use **px** in styles, you have to fix it
```
const RadioType = {
    ROUND: 'round',
    CARD: 'card',
} as const;

type Properties<T extends FieldValues> = {
    name: FieldPath<T>;
    id: string;
    label: string;
    value: string;
    control: Control<T>;
    type: ValueOf<typeof RadioType>;
    className?: string;
};

const Radio = <T extends FieldValues>({
    name,
    id,
    label,
    value,
    control,
    type,
    className = '',
}: Properties<T>): JSX.Element => {
    const { field } = useFormController({ name, control });

    const radioTypeToClasses: Record<
        ValueOf<typeof RadioType>,
        {
            container: string;
            input: string;
            inputChecked: string;
            label: string;
            labelChecked: string;
        }
    > = {
        [RadioType.ROUND]: {
            container: 'flex items-center py-1',
            input: 'peer/radio border-lm-grey-500 relative h-4 w-4 cursor-pointer appearance-none rounded-full border-2 bg-transparent',
            inputChecked:
                'checked:border-lm-yellow-100 checked:after:bg-lm-yellow-100 checked:after:absolute checked:after:left-1/2 checked:after:top-1/2 checked:after:h-2 checked:after:w-2 checked:after:rounded-full checked:after:[transform:translate(-50%,-50%)]',
            label: 'text-lm-grey-500 ml-2 text-base',
            labelChecked: 'peer-checked/radio:text-lm-grey-200',
        },
        [RadioType.CARD]: {
            container: 'rounded-r-lg',
            input: 'peer/radio hidden',
            inputChecked: '',
            label: 'text-lm-grey-200 bg-lm-black-100 table-cell h-[37px] cursor-pointer px-[24px] py-[9px] text-center align-middle text-base',
            labelChecked:
                'peer-checked/radio:text-lm-black-100 peer-checked/radio:bg-lm-yellow-100',
        },
    };

    return (
        <div className={getValidClassNames(radioTypeToClasses[type].container)}>
            <input
                {...field}
                id={id}
                value={value}
                checked={field.value === value}
                type="radio"
                className={getValidClassNames(
                    radioTypeToClasses[type].input,
                    radioTypeToClasses[type].inputChecked,
                )}
            />
            <label
                htmlFor={id}
                className={getValidClassNames(
                    radioTypeToClasses[type].label,
                    radioTypeToClasses[type].labelChecked,
                    className,
                )}
            >
                {label}
            </label>
        </div>
    );
};
```

Comment (stpalamar) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx:1]: I used **peer-\*** modifier for styling label depend on input checked. 
You can read more about it in [docs](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state)

File: frontend/src/bundles/common/components/radio-card/radio-card.tsx (hunk 4 above)
Comment (anton-otroshchenko) [reply frontend/src/bundles/common/components/radio-card/radio-card.tsx]: checked because I did not find the usage of it in the component

**Review by ArtemLymarenko — DISMISSED** [review]

File: frontend/src/bundles/common/enums/radio-type.enum.ts
Comment (stpalamar) [inline frontend/src/bundles/common/enums/radio-type.enum.ts:1]: You should keep RadioType directly in **radio.tsx** or maybe create enums inside **radio** folder and put it there because it is type only for radio component not for entire frontend

Comment (valery-chumak) [reply frontend/src/bundles/common/enums/radio-type.enum.ts:1]: @stpalamar Shouldn't we use RadioType as property to Radio from all components where we use radio?
 For example, `<Radio
                        id="radio-female"
                        name="gender"
                        label="Female"
                        value={Gender.FEMALE}
                        control={control}
                        type={RadioType.CARD}
                        className="w-83"
                    />`. I think it is the same as for RadioType and as for ComponentSize which is also stored in common enums. Or am I missing something?

Comment (valery-chumak) [reply frontend/src/bundles/common/enums/radio-type.enum.ts:1]: I think it is the same as for RadioType and as for ComponentSize which is also stored in common enums. Or am I missing something?

**Comment by valery-chumak** [comment]
Added responsive design
Снимок экрана 2024-02-24 170036
Снимок экрана 2024-02-24 170102

File: backend/src/common/types/service.type.ts [hunk 9]
```diff
@@ -1,10 +1,15 @@
...
 type Service<T = unknown> = {
     find(query: Record<string, T>): Promise<T>;
     findAll(): Promise<{
         items: T[];
     }>;
     create(payload: unknown): Promise<T>;
-    update(): Promise<T>;
+    update(
+        id: number,
+        updatedDetails: UserUpdateProfileRequestDto,
```
Comment (jhladkov) [inline backend/src/common/types/service.type.ts]: I think we shouldn't set UserUpdateProfileRequestDto in global service type because we implement Service in many places. For example, for goals or workouts we need to update some data and we will get an error because in update we have to pass UserUpdateProfileRequestDto.

File: frontend/src/bundles/common/enums/radio-type.enum.ts
Comment (stpalamar) [reply frontend/src/bundles/common/enums/radio-type.enum.ts:1]: ComponentSize is general type for all components so that is why it is in common enums. But RadioType is only type for Radio component and we should keep it in radio folder or just in radio.tsx like ButtonType in button.tsx

File: backend/src/bundles/users/enums/enums.ts [hunk 10]
```diff
@@ -1,3 +1,9 @@
 export { UserAttributes } from './user-attributes.enum.js';
 export { UserDetailsAttributes } from './user-details-attributes.enum.js';
 export { Gender, UsersApiPath } from 'shared';
+export {
+    AuthApiPath,
+    HttpCode,
+    HttpError,
```
Comment (stpalamar) [inline backend/src/bundles/users/enums/enums.ts]: You have HttpCode, HttpError in **backend/src/common/http/http.ts**, I guess you don't need this export here

File: backend/src/bundles/users/user.controller.ts [hunk 11]
```diff
@@ -1,12 +1,17 @@
...
+} from '~/bundles/users/users.js';
 import {
     type ApiHandlerOptions,
     type ApiHandlerResponse,
-    BaseController,
 } from '~/common/controller/controller.js';
+import { BaseController } from '~/common/controller/controller.js';
 import { ApiPath } from '~/common/enums/enums.js';
-import { HttpCode } from '~/common/http/http.js';
+import { HttpCode, HttpError } from '~/common/http/http.js';
```
Comment (stpalamar) [inline backend/src/bundles/users/user.controller.ts:13]: like here

File: backend/src/bundles/users/user.repository.ts [hunk 12]
```diff
@@ -2,6 +2,9 @@ import { UserEntity } from '~/bundles/users/user.entity.js';
 import { type UserModel } from '~/bundles/users/user.model.js';
 import { type Repository } from '~/common/types/types.js';
 
+import { HttpCode, HttpError, UserValidationMessage } from './enums/enums.js';
```
Comment (stpalamar) [inline backend/src/bundles/users/user.repository.ts]: import HttpCode, HttpError from common

File: backend/src/common/types/service.type.ts [hunk 13]
```diff
@@ -4,7 +4,7 @@ type Service<T = unknown> = {
         items: T[];
     }>;
     create(payload: unknown): Promise<T>;
-    update(): Promise<T>;
+    update(id: number, updatedDetails: unknown): Promise<T | null>;
```
Comment (stpalamar) [inline backend/src/common/types/service.type.ts]:
```suggestion
    update(query: Record<string, T>, payload: unknown): Promise<T | null>;
```
I think better use name **query** and **payload** as it is general type, so in some cases we find item to update not only by id

File: frontend/src/bundles/profile/pages/profile.tsx [hunk 14]
```diff
@@ -0,0 +1,29 @@
+import { DataStatus } from '~/bundles/common/enums/enums.js';
+import {
+    useAppDispatch,
+    useAppSelector,
+    useCallback,
+} from '~/bundles/common/hooks/hooks.js';
+import { type UserUpdateProfileRequestDto } from '~/bundles/users/users.js';
+
+import { actions as authActions } from '../../auth/store/auth.js';
```
Comment (stpalamar) [inline frontend/src/bundles/profile/pages/profile.tsx]:
```suggestion
import { actions as authActions } from '~/bundles/auth/store/auth.js';
```

File: frontend/tailwind.config.js [hunk 15]
```diff
@@ -70,6 +70,9 @@ export default {
                 sans: ['Manrope', ...defaultTheme.fontFamily.sans],
             },
             backgroundImage: {
+                'auth': "linear-gradient(to right, #E0FE10, transparent), linear-gradient(to right, #2A2F37, transparent), url('./src/assets/img/auth-bg.png')",
+                'rectangle':
+                    'linear-gradient(89.83deg, #E0FE10 36.42%, rgba(224, 254, 16, 0) 125.23%)',
```
Comment (stpalamar) [inline frontend/tailwind.config.js]: why we need this? I guess mistake during resolving conflicts)

File: backend/src/bundles/users/user-details.model.ts [hunk 16]
```diff
@@ -26,6 +26,8 @@ class UserDetailsModel extends AbstractModel {
     public static override get tableName(): string {
         return DatabaseTableName.USER_DETAILS;
     }
+
+    [key: string]: unknown;
```
Comment (dimapopovych) [inline backend/src/bundles/users/user-details.model.ts:30]: why do you need this?

File: backend/src/bundles/users/user.controller.ts [hunk 17]
```diff
@@ -1,12 +1,17 @@
+import { UserValidationMessage } from 'shared';
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.controller.ts]: import

File: backend/src/bundles/users/user.controller.ts [hunk 18]
```diff
@@ -95,6 +100,20 @@ class UserController extends BaseController {
                     }>,
                 ),
         });
+
+        this.addRoute({
+            path: `${UsersApiPath.UPDATE_USER}/:userId`,
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.controller.ts]: why are you passing userId as param?

File: backend/src/bundles/users/user.controller.ts [hunk 19]
```diff
@@ -167,6 +186,53 @@ class UserController extends BaseController {
...
+                        message: UserValidationMessage.BIRTHDATE_FORMAT,
+                        status: HttpCode.BAD_REQUEST,
+                    });
+                } else {
+                    const formattedDate =
+                        parsedDate.toLocaleDateString('en-GB');
+
+                    updatedUser.dateOfBirth = formattedDate;
+                }
+            }
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.controller.ts]: Why do we need all this logic here? Can't we simply pass the date from the frontend as an ISO string, return it as an ISO string as well, and then just change the format when displaying the date on the frontend?

File: backend/src/bundles/users/user.service.ts [hunk 20]
```diff
@@ -47,9 +51,50 @@ class UserService implements Service {
...
+                id: userId,
+            });
+            if (existingUser) {
+                const updatedUserDetails: Partial<UserDetailsModel> = {};
+                for (const property of Object.keys(payload)) {
+                    const value = payload[property];
+                    if (value) {
+                        updatedUserDetails[property] =
+                            property === 'weight' || property === 'height'
+                                ? Number(payload[property])
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.service.ts]: Seems like an error will occur if users passes something like "70 kg" as weight, since type conversion will return NaN. 
Why do we even store weight/height as numbers, but passing it in request as strings?

**Review by dimapopovych — CHANGES_REQUESTED** [review]

File: backend/src/bundles/users/user.controller.ts (hunk 18 above)
Comment (dimapopovych) [reply backend/src/bundles/users/user.controller.ts]: Simply retrieve user from options

File: backend/src/bundles/users/user-details.model.ts (hunk 16 above)
Comment (valery-chumak) [reply backend/src/bundles/users/user-details.model.ts:30]: For this part of code where I use property as string
`const updatedUserDetails: Partial<UserDetailsModel> = {};
for (const property of Object.keys(payload)) {
                    const value = payload[property];
                    if (value) {
                        updatedUserDetails[property] =
                            property === 'weight' || property === 'height'
                                ? Number(payload[property])
                                : payload[property];
                    }
 }`
 If i remove it I get this error notification `Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Partial<UserDetailsModel>'.
  No index signature with a parameter of type 'string' was found on type 'Partial<UserDetailsModel>'.`

File: backend/src/bundles/users/user.service.ts (hunk 20 above)
Comment (valery-chumak) [reply backend/src/bundles/users/user.service.ts]: In database and `userDetailsModel `weight/height are numbers, but in specifications for Profile Settings component it is written that user can input digits,letters etc. So, the type of weight/height in `UserUpdateProfileRequestDto `is string. So, I was extracting just numbers in a string on frontend and passing them to backend. And on backend convert string with numbers to a number type. 🫠

Comment (dimapopovych) [reply backend/src/bundles/users/user.service.ts]: So, users can enter any string, but we're only storing the numbers from that string, right? Do you find this weird? I would ask the authors of these specs about the reasoning behind this approach.

Comment (valery-chumak) [reply backend/src/bundles/users/user.service.ts]: So, these are specs)
image
And here is our database)
image

File: backend/src/bundles/users/user.controller.ts (hunk 19 above)
Comment (valery-chumak) [reply backend/src/bundles/users/user.controller.ts:223]: So, when user inputs dateOfBirth I should made a validation of it to be format "dd/mm/yyyy" as was told in specs, so the type of `dateOfBirth `is string in `UserUpdateProfileRequestDto`, but in database it is Date type, so I was converting  it to Date on backend. Or how should I handle it correctly?)

File: backend/src/bundles/users/user.service.ts (hunk 20 above)
Comment (dimapopovych) [reply backend/src/bundles/users/user.service.ts]: I'd recommend asking the QA team about the reasoning behind this format. We can then decide whether to change it to number inputs on the frontend or adjust the database structure to store strings for these fields. Currently, users can enter any string on the frontend, and only the numbers from that string will be stored, seems like unexpected behavior to me. The intention might have been to store strings these fields as strings, but I'm unsure if this is the best approach, so it's worth discussing with the QA team.

File: backend/src/bundles/users/user.repository.ts [hunk 21]
```diff
@@ -110,6 +113,47 @@ class UserRepository implements Repository {
...
+        ] as Partial<UserDetailsModel>;
+        try {
+            const user = await this.userModel.query(trx).findById(userId);
+
+            if (!user) {
+                throw new HttpError({
+                    message: UserValidationMessage.USER_NOT_FOUND,
+                    status: HttpCode.NOT_FOUND,
+                });
+            }
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.repository.ts]: Do we need this check as we already checking users exist stance in auth plugin?

File: backend/src/bundles/users/user.repository.ts [hunk 22]
```diff
@@ -110,6 +113,47 @@ class UserRepository implements Repository {
             .execute();
     }
 
+    public async update(
+        query: Record<string, unknown>,
+        payload: Record<string, Partial<UserDetailsModel>>,
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.repository.ts]: Maybe it's worth to create `toProfileUpdate` or so method in entity, simirarly as for creation?

File: backend/src/bundles/users/user.service.ts [hunk 23]
```diff
@@ -49,10 +53,48 @@ class UserService implements Service {
     }
 
     public async update(
+        query: Record<string, number>,
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.service.ts]: probably would be better to change it to updateProfileById or so I don't think that we will update by another criteria

File: backend/src/bundles/users/user.service.ts [hunk 24]
```diff
@@ -49,10 +53,48 @@ class UserService implements Service {
...
+        payload: UserUpdateProfileRequestDto,
+    ): Promise<UserAuthResponseDto | null> {
+        try {
+            const userId = query['id'] as number;
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.service.ts]: and you are anyway relying on presence id in this query, if there will be no id present this will drop exception

File: backend/src/bundles/users/user.service.ts [hunk 25]
```diff
@@ -49,10 +53,48 @@ class UserService implements Service {
...
+                id: userId,
+            });
+            if (existingUser) {
+                const updatedUserDetails: Partial<UserDetailsModel> = {};
+                for (const property of Object.keys(payload)) {
+                    const value = payload[property];
+                    if (value) {
+                        updatedUserDetails[property] = payload[property];
+                    }
+                }
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.service.ts]: seems like user will be unable to remove nickname for example with this approach, since this update will be ignored.` toUpdateProfile` could solve this and simplify everything

File: backend/src/bundles/users/user.service.ts [hunk 26]
```diff
@@ -49,10 +53,48 @@ class UserService implements Service {
...
 
     public async update(
+        query: Record<string, number>,
+        payload: UserUpdateProfileRequestDto,
+    ): Promise<UserAuthResponseDto | null> {
+        try {
+            const userId = query['id'] as number;
+            const existingUser = await this.userRepository.find({
+                id: userId,
+            });
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.service.ts]: Already checked in plugin and repository, that's a lot of unnecessary db queries.

File: backend/src/migrations/20240216181434_add_columns_to_user_details_table.ts [hunk 27]
```diff
@@ -27,7 +27,7 @@ async function up(knex: Knex): Promise<void> {
     await knex.schema.alterTable(TABLE_NAME, (table) => {
         table.text(ColumnName.AVATAR_URL).nullable();
         table.string(ColumnName.USERNAME).unique().nullable();
-        table.date(ColumnName.DATE_OF_BIRTH).nullable();
+        table.dateTime(ColumnName.DATE_OF_BIRTH).nullable();
```
Comment (dimapopovych) [inline backend/src/migrations/20240216181434_add_columns_to_user_details_table.ts]: Date will be enough, also don't change existing migrations, it's already deployed to stage

File: shared/src/bundles/users/types/user-update-profile-request-dto.type.ts [hunk 28]
```diff
@@ -0,0 +1,16 @@
...
+    id: number | null;
+    fullName?: string | null;
+    username?: string | null;
+    avatarUrl?: string | null;
+    dateOfBirth?: string | null;
+    weight?: number | null | '';
+    height?: number | null | '';
+    gender?: ValueOf<typeof Gender>;
+    [key: string]: string | number | null;
+};
```
Comment (dimapopovych) [inline shared/src/bundles/users/types/user-update-profile-request-dto.type.ts]: id is redundant, seems like every field should be required, avatar will be uploaded with separate request, index in this type is also redundant

**Review by dimapopovych — CHANGES_REQUESTED** [review]

File: backend/src/bundles/users/user.service.ts (hunk 23 above)
Comment (valery-chumak) [reply backend/src/bundles/users/user.service.ts]: It was the simple `id` instead of `query`, but as `updatePassword` also use Repository type update I changed it to the `query` for mine implementation too, also I think I can't rename this method to `updateProfileById` because the service.type has only update method. And if I add a new one, it will ask to implement this method all through the other services in the app

```
type Service<T = unknown> = {
    find(query: Record<string, T>): Promise<T>;
    
    findAll(): Promise<{
        items: T[];
    }>;
    
    create(payload: unknown): Promise<T>;
    
    update(
        query: Record<string, T>,
        payload: Record<string, unknown>,
    ): Promise<T | null>;
    
    delete(payload: unknown): Promise<boolean>;
};
```

File: backend/src/bundles/users/user.repository.ts (hunk 21 above)
Comment (valery-chumak) [reply backend/src/bundles/users/user.repository.ts]: Here `const user: UserModel | undefined` so it is need to be checked if it is not undefined.

File: backend/src/bundles/users/user.service.ts (hunk 25 above)
Comment (valery-chumak) [reply backend/src/bundles/users/user.service.ts]: Nickname is stored as a username property because it was already used everywhere as a username and also to avoid such cases

File: backend/src/bundles/users/user.service.ts (hunk 23 above)
Comment (dimapopovych) [reply backend/src/bundles/users/user.service.ts]: You don't need to add it to the service type, these annotations here mostly to enforce naming conventions for common methods.

File: backend/src/bundles/users/user.repository.ts (hunk 21 above)
Comment (dimapopovych) [reply backend/src/bundles/users/user.repository.ts]: Yeah, that's fine then, but the repository still can't throw http related errors, simply return null in this case.

File: backend/src/bundles/users/user.service.ts (hunk 25 above)
Comment (dimapopovych) [reply backend/src/bundles/users/user.service.ts]: i'm talking about case where you will receive request
```
{
  "weight": 50,
  "username": null,
  ...other fields
}
```
with payload above. This will not delete username for user, since you are checking for truthy values, same for empty string/0.
Or am I missing something?

Comment (valery-chumak) [reply backend/src/bundles/users/user.service.ts]: Oh, I thought that the empty query on fields should not remove the previous data. But as I understood it should?

File: backend/src/bundles/users/user.repository.ts [hunk 29]
```diff
@@ -110,6 +111,38 @@ class UserRepository implements Repository {
...
+        const trx = await this.userModel.startTransaction();
+        try {
+            const user = await this.userModel.query(trx).findById(userId);
+
+            if (!user) {
+                return null;
+            }
+            await user.$relatedQuery('userDetails', trx).patch(payload);
+
+            const userDetails = await user.$relatedQuery('userDetails', trx);
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.repository.ts]: Could use .returning('*') to retrieve data with one query

File: backend/src/bundles/users/user.service.ts [hunk 30]
```diff
@@ -48,6 +52,34 @@ class UserService implements Service {
...
+    ): Promise<UserAuthResponseDto | null> {
+        try {
+            const userId = query['id'] as number;
+
+            const updatedUserDetails: Partial<UserDetailsModel> = {};
+            for (const property of Object.keys(payload)) {
+                const value = payload[property];
+                updatedUserDetails[property] = value || null;
+                updatedUserDetails.id = userId;
+            }
```
Comment (dimapopovych) [inline backend/src/bundles/users/user.service.ts]: why do you need this whole part?

File: backend/src/bundles/users/user.service.ts (hunk 24 above)
Comment (dimapopovych) [reply backend/src/bundles/users/user.service.ts]: not resolved

File: backend/src/common/types/service.type.ts [hunk 31]
```diff
@@ -5,9 +5,9 @@ type Service<T = unknown> = {
     }>;
     create(payload: unknown): Promise<T>;
     update(
-        query: Record<string, unknown>,
+        query: Record<string, T>,
```
Comment (dimapopovych) [inline backend/src/common/types/service.type.ts]: Why do you need this change?

**Review by dimapopovych — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 32]
```diff
@@ -0,0 +1,229 @@
...
+            setValue('fullName', fullName || '');
+            setValue('username', username || '');
+            setValue('dateOfBirth', configureDateString(dateOfBirth) || '');
+            setValue('weight', weight || '');
+            setValue('height', height || '');
+            setValue('gender', gender || '');
+
+            setValuesDefault(true);
+        }
+    }, [user, setValue, valuesDefault]);
```
Comment (dimapopovych) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: Could you map user and use it as default values?

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 33]
```diff
@@ -0,0 +1,229 @@
...
+    isLoading: boolean;
+};
+
+const ProfileSettings: React.FC<Properties> = ({ onSubmit, isLoading }) => {
+    const [valuesDefault, setValuesDefault] = useState(false);
+    const { user } = useAppSelector(({ auth }) => ({
+        user: auth.user,
+    }));
+
+    const { control, errors, reset, getValues, setValue } =
```
Comment (dimapopovych) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: Is it impossible to use handleSubmit from hook form?

File: shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts [hunk 34]
```diff
@@ -0,0 +1,98 @@
...
+        ]),
+        dateOfBirth: z.union([
+            z
+                .string()
+                .regex(
+                    UnicodePattern.BIRTHDATE_PATTERN,
+                    UserValidationMessage.BIRTHDATE_FORMAT,
+                )
+                .nullable(),
+            z.literal(''),
```
Comment (dimapopovych) [inline shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts:48]: zod has built-in datetime strings validation

File: shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts [hunk 35]
```diff
@@ -0,0 +1,98 @@
...
+                    (value) =>
+                        value.length <= UserValidationRule.WEIGHT.MAX_LENGTH ||
+                        value.length >= UserValidationRule.WEIGHT.MIN_LENGTH,
+                    {
+                        message: UserValidationMessage.WEIGHT_LENGTH,
+                    },
+                )
+                .nullable(),
+            z.literal(''),
+        ]),
```
Comment (dimapopovych) [inline shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts]: could we try to use z.coerce.number for such fields?

File: shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts (hunk 34 above)
Comment (valery-chumak) [reply shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts:48]: It has, but I need only to accept one specific format of date which is dd/mm/yyyy and according to zod documentation the built-in validation of date will pass for all other date formats (for example "2023-01-10")

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx (hunk 33 above)
Comment (valery-chumak) [reply frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: I think I can)

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 36]
```diff
@@ -0,0 +1,232 @@
...
+                }
+            }
+            setValuesDefault(true);
+        }
+    }, [user, setValue, valuesDefault]);
+
+    const handleFormSubmit = useCallback(
+        (event_: React.BaseSyntheticEvent): void => {
+            void handleSubmit((data) => {
+                if (Object.keys(errors).length === 0) {
```
Comment (dimapopovych) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: this check is unnecessary since this callback will be called only if validation is successful

File: shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts [hunk 37]
```diff
@@ -0,0 +1,98 @@
...
+        gender: z.union([
+            z.literal('male'),
+            z.literal('female'),
+            z.literal('prefer not to say'),
+        ]),
```
Comment (dimapopovych) [inline shared/src/bundles/users/validation-schemas/user-update-profile.validation-schema.ts]: can we replace this with enum?

**Review by dimapopovych — CHANGES_REQUESTED** [review]

**Review by dimapopovych — DISMISSED** [review]

**Review by nikita-remeslov — DISMISSED** [review]
Not the best implementation, but let's move on

**Review by nikita-remeslov — APPROVED** [review]
