### PR TITLE
LIME-303: Fix non Integer weight/height value

### LINKED ISSUE #303: BUG: Server error message is received when users saves Profile information with with dot in value of Weight and Height
### Describe your issue

Server error message informing that data type is wrong  is received when users saves Profile information with dot in value of Weight and Height, 400 status code of request

### Steps to reproduce

1. Open https://live-in-motion-everyday.com/sign-in, login with valid credentials.
2. Navigate to Personal information page, clicking on gear icon in header, open DevTools.
3. Enter float values in the fields Weight and Height - e.g. 80.5 and 170.5
4. Click on Save
5. Check if data were saved, pay attention to Network tab in DevTools

### What was the actual result?

Server error message informing that data type is wrong  is received when users saves Profile information with dot in value of Weight and Height, 400 status code of request

### What was the expected result?

User can save value of Weight with dot for the accuracy of data up to grams

### Put here any screenshots or videos (optional)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/5678f256-1412-4715-a277-3c6143a7cc0b

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

### LINKED ISSUE #305: BUG: Error message for invalid format of Weight and Height in Profile information is not user-friendly
### Describe your issue

After negative validation on non-numeric value (letters, spaces, special characters excluding dot) of Weight and Height in Profile information, user is displayed error message "Expected number, received nan"
After negative validation on more than max value of Height in Profile information, user is displayed error message "Heiht should be from 0 to 0 sm"

### Steps to reproduce

1. Open https://live-in-motion-everyday.com/sign-in, login with valid credentials.
2. Navigate to Personal information page, clicking on gear icon in header.
3. Enter non-numeric value in the field Weight e.g. letters
4. Enter non-numeric value in the fields Heigh e.g. letters, switch focus to another element of field
5. Check if displayed error message is informative and user-friendly
6. Enter value more 300 in the field Height
7. Check if displayed error message is informative and user-friendly

### What was the actual result?

After negative validation on non-numeric value (letters, spaces, special characters excluding dot) of Weight and Height in Profile information, user is displayed error message "Expected number, received nan"
After negative validation on more than 300 value of Height in Profile information, user is displayed error message "Heiht should be from 0 to 0 sm"

### What was the expected result?

After negative validation on non-numeric value (letters, spaces, special characters excluding dot) of Weight and Height in Profile information, user is displayed informative and user friendly error message - e.g. Weight should only contain numbers and a decimal point or Please enter valid weight
After negative validation on more than 300 value of Height in Profile information, user is displayed error message "Heiht should be from 0 to 300 sm"

### Put here any screenshots or videos (optional)

image
image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by valery-chumak**

### CODE REVIEW

File: frontend/src/bundles/common/helpers/convert-height/convert-height-to-cm.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+const convertHeightToCentimeters = (
+    height: string | number | null,
+): number | null => {
+    if (height === null) {
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/common/helpers/convert-height/convert-height-to-cm.ts]:
```suggestion
    if (!heightl) {
```

File: frontend/src/bundles/common/helpers/convert-height/convert-height-to-cm.ts [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+        return null;
+    }
+
+    const heightInMm =
+        typeof height === 'string' ? Number.parseFloat(height) : height;
+
+    return Number.isNaN(heightInMm)
+        ? null
+        : Math.round((heightInMm / 10) * 10) / 10;
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/common/helpers/convert-height/convert-height-to-cm.ts]: please prevent magic values

File: frontend/src/bundles/common/helpers/convert-height/convert-height-to-mm.ts [hunk 3]
```diff
@@ -0,0 +1,14 @@
+const convertHeightToMillimeters = (
+    height: string | number | null,
+): number | null => {
+    if (height === null) {
+        return null;
+    }
+
+    const heightInCm =
+        typeof height === 'string' ? Number.parseFloat(height) : height;
+
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/common/helpers/convert-height/convert-height-to-mm.ts]: duplicating logic, maybe we can somehow make a one helper instead of three

File: frontend/src/bundles/common/helpers/convert-weight/convert-weight-to-grams.ts [hunk 4]
```diff
@@ -0,0 +1,16 @@
+const convertWeightToGrams = (
+    weight: string | number | null,
+): number | null => {
+    if (weight === null) {
+        return null;
+    }
+
+    const weightInKg =
+        typeof weight === 'string' ? Number.parseFloat(weight) : weight;
+
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/common/helpers/convert-weight/convert-weight-to-grams.ts]: same here

File: frontend/src/bundles/common/helpers/convert-weight/convert-weight-to-kilograms.ts [hunk 5]
```diff
@@ -0,0 +1,8 @@
+const convertWeightToKilograms = (grams: number | null): number | null => {
+    if (grams) {
+        return grams / 1000;
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/common/helpers/convert-weight/convert-weight-to-kilograms.ts]: magic value

**Review by anton-otroshchenko — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/common/helpers/convert-height/convert-height-to-mm.ts (hunk 3 above)
Comment (valery-chumak) [reply frontend/src/bundles/common/helpers/convert-height/convert-height-to-mm.ts]:
```
import { KG_TO_GRAMS_CONVERSION_FACTOR, MM_TO_CM_CONVERSION_FACTOR, ROUNDING_FACTOR } from './constants/constants.js';

const convertToTargetUnit = (
  value: string | number | null,
  conversionFactor: number,
  roundingFactor: number = 1
): number | null => {
  if (!value) {
    return null;
  }

  const numericValue = typeof value === 'string' ? Number.parseFloat(value) : value;

  return Number.isNaN(numericValue)
    ? null
    : Math.round(numericValue * conversionFactor * roundingFactor) / roundingFactor;
};

const convertWeightToGrams = (weight: string | number | null): number | null => {
  return convertToTargetUnit(weight, KG_TO_GRAMS_CONVERSION_FACTOR, ROUNDING_FACTOR);
};

const convertHeightToMillimeters = (height: string | number | null): number | null => {
  return convertToTargetUnit(height, 1, MM_TO_CM_CONVERSION_FACTOR);
};

const convertHeightToCentimeters = (height: string | number | null): number | null => {
  return convertToTargetUnit(height, MM_TO_CM_CONVERSION_FACTOR, MM_TO_CM_CONVERSION_FACTOR);
};

export { convertWeightToGrams, convertHeightToMillimeters, convertHeightToCentimeters };
```
@anton-otroshchenko You mean something like this? I don't know how it will be better to make

Comment (anton-otroshchenko) [reply frontend/src/bundles/common/helpers/convert-height/convert-height-to-mm.ts]: Yeah, I thinks thats better

File: frontend/src/bundles/common/helpers/convert-metrics/convert-metrics.ts
Comment (nikita-remeslov) [inline frontend/src/bundles/common/helpers/convert-metrics/convert-metrics.ts:1]: 1 helper = 1 fiel

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/common/helpers/convert-metrics/convert-metrics.ts
Comment (valery-chumak) [reply frontend/src/bundles/common/helpers/convert-metrics/convert-metrics.ts:1]: @anton-otroshchenko recommended me to make 1 file. Okay, I will return the old version)

**Review by nikita-remeslov — APPROVED** [review]
