### PR TITLE
LIME-222:  Fixed reset password page with expired token

### LINKED ISSUE #222: BUG: The user can access Reset password page with expired token
### Describe your issue

The user can access Reset password page with expired token.

### Steps to reproduce

1. Go to the [reset password page](http://lime.eu-north-1.elasticbeanstalk.com/reset-password/eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjU4LCJleHAiOjE3MDkxNDQ0ODN9.Sey6MJxjo2Bglgyl4XqU2LGfyZJcA8hY2dj3kiHml8M) using the expired link
2. Pay attention to the page displayed 

### What was the actual result?

The user can access Reset password page with expired token.

### What was the expected result?

The user is redirected to the Sign In page after trying to access Reset password page with expired token. "The password reset token you used has expired" error is displayed on the Sign In page

### Put here any screenshots or videos (optional)

Image

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/124812752/f1412ef0-f645-475b-bc56-aa8e25aa27e1

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by SergiiTernytskyi**
Fixed reset password page with an expired token

https://www.loom.com/share/b209d1eba652414e9204f1b1c575f53a

### CODE REVIEW

**Review by stpalamar — APPROVED** [review]

**Review by dimapopovych — APPROVED** [review]

File: frontend/src/bundles/password-reset/pages/password-reset.tsx [hunk 1]
```diff
@@ -22,14 +22,17 @@ import {
     type PasswordResetPayload,
     type PasswordResetRequestDto,
 } from '~/bundles/password-reset/types/types.js';
+import { notificationManager } from '~/framework/notification/notification.js';
 
 import { PasswordResetSuccessMessage } from '../components/components.js';
 
+const errorText = 'The password reset link you used has expired';
```
Comment (dimapopovych) [inline frontend/src/bundles/password-reset/pages/password-reset.tsx]: but let's move this to separate file as constant

Comment (SergiiTernytskyi) [reply frontend/src/bundles/password-reset/pages/password-reset.tsx]: all done

**Review by nikita-remeslov — APPROVED** [review]
