### PR TITLE
LIME-485: Fix application error

### LINKED ISSUE #485: BUG: Application error is displayed on Friends page after clicking on user's card
### Describe your issue

Application error is displayed on Friends page after clicking on user's card

### Steps to reproduce

Pre-condition: user is logged in on https://live-in-motion-everyday.com/sign-in

1. Navigate to Friends page
2. Click on User card
3. Pay attention to the page displayed

### What was the actual result?

Application error is displayed on Friends page after clicking on user's card

### What was the expected result?

Friends page is displayed with selected User info component

### Put here any screenshots or videos (optional)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/bdd6c5e8-edb8-46a1-8422-4fd594de8114

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Blocker (S1)

### PR DESCRIPTION
**Pull request by VasylynaKolodiy**

### CODE REVIEW

**Review by valery-chumak — DISMISSED** [review]

**Review by SergiiTernytskyi — DISMISSED** [review]

**Review by stpalamar — DISMISSED** [review]

**Review by valery-chumak — DISMISSED** [review]

File: frontend/src/bundles/friends/components/friend-details/friend-details.tsx [hunk 1]
```diff
@@ -93,9 +93,12 @@ const FriendDetails = ({
             </div>
 
             <div className="mb-4 flex w-full items-center justify-between">
-                <h3 className="text-lm-grey-200 text-xl font-extrabold leading-6">
-                    Achievements
-                </h3>
+                {achievements?.length > 0 && (
```
Comment (dimapopovych) [inline frontend/src/bundles/friends/components/friend-details/friend-details.tsx]: I think it should be fixed on backend, seems like we are returning either error or null if user don't have achievements. should return empty array.

**Review by dimapopovych — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/friends/components/friend-details/friend-details.tsx (hunk 1 above)
Comment (VasylynaKolodiy) [reply frontend/src/bundles/friends/components/friend-details/friend-details.tsx]: fixed
