### PR TITLE
LIME-487:  Fixed redirect user when token expired

### LINKED ISSUE #487: BUG: User is not redirected to login page when token expires
### Describe your issue

User is not redirected to login page when token expires. Blank screen with Invalid token error message is displayed to the user when he tries to reach another page

### Steps to reproduce

1. Change token expiration time to 1 minute
2. Log in on https://live-in-motion-everyday.com/sign-in
3. Wait more than 1 minute, refresh the page
4. Pay attention to the page displayed

### What was the actual result?

User is not redirected to login page when token expires. Blank screen with Invalid token error message is displayed to the user when he tries to reach another page

### What was the expected result?

User is automatically logged out and redirected to login page when token expires. 

### Put here any screenshots or videos (optional)

image
image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Blocker (S1)

### PR DESCRIPTION
**Pull request by jhladkov**

### CODE REVIEW

**Review by stpalamar — DISMISSED** [review]

File: frontend/src/app/app.tsx [hunk 1]
```diff
@@ -41,6 +46,13 @@ const App: React.FC = () => {
         void refreshUser();
     }, [dispatch]);
 
+    useEffect(() => {
+        if (authDataStatus === DataStatus.REJECTED) {
+            void storage.drop(StorageKey.TOKEN);
+            navigate(AuthApiPath.SIGN_IN);
+        }
+    }, [authDataStatus, navigate]);
+
```
Comment (dimapopovych) [inline frontend/src/app/app.tsx]: I believe we should have handling for this in error middleware, maybe it's worth to just fix it there?

**Comment by ivanbilobrov07** [comment]
image
image
I think that the issue is that from server we dont get the status, so check in the middleware fails

**Comment by jhladkov** [comment]
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/74872088/7d8ac702-6d43-423f-a0d6-398b4a54ce28

**Review by nikita-remeslov — APPROVED** [review]
