### PR TITLE
LIME-279: Elements of Goal widget on Home page don't correspond the design

### LINKED ISSUE #279: BUG: Elements of Goal widget on Home page don't correspond the design
### Describe your issue

 - [x] Label of activity is not centered aligning activity icon 
 - [x] Font color of label Track your daily activities is different from design
 - [x] Activity label is not responsive

### Steps to reproduce

1. Open https://live-in-motion-everyday.com/
2. Being redirected to Sign In page, login with valid credentials.
3. Being redirected to Home page, compare elements of Goal widget with Figma design.
4. Minimize window up to width 640, check the responsiveness of activity label

### What was the actual result?

Label of activity is not centered aligning activity icon
Font color of label Track your daily activities is different from design - #2A2F37 
 Activity label doesn't respond to the minimizing of the window width

### What was the expected result?

Elements of Goal widget on Home page correspond the Figma design and respond to the minimizing of the window width

### Put here any screenshots or videos (optional)

image
image
image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by SergiiTernytskyi**
Goal widget styles changed
Screenshot_8

### CODE REVIEW

**Review by valery-chumak — DISMISSED** [review]

File: frontend/src/bundles/overview/components/circle-progress/circle-progress.tsx [hunk 1]
```diff
@@ -33,16 +33,16 @@ const CircleProgress = ({
...
         circumference - (value / target) * circumference;
 
     return (
         <div className="relative flex items-center justify-center">
             <svg
-                height={radius * 2}
-                width={radius * 2}
+                height={outerRadius * 2}
+                width={outerRadius * 2}
                 style={{ transform: 'rotate(90deg)' }}
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/overview/components/circle-progress/circle-progress.tsx]: Even though it wasn't your code originally but can you please remove magic numbers here

**Review by nikita-remeslov — APPROVED** [review]
