### PR TITLE
LIME-258: Fixed navigation link

### LINKED ISSUE #258: Fix navigation link

### PR DESCRIPTION
**Pull request by ArtemLymarenko**

### CODE REVIEW

File: frontend/src/bundles/common/components/header/components/navigation/navigation.tsx [hunk 1]
```diff
@@ -20,18 +20,16 @@ const Navigation = ({ avatarUrl }: Properties): JSX.Element => {
...
                 <li>
-                    <Link to={AppRoute.PROFILE}>
-                        <img
-                            src={avatarUrl || defaultAvatar}
-                            alt="avatar"
-                            className={styles['avatar']}
-                        />
-                    </Link>
+                    <img
+                        src={avatarUrl || defaultAvatar}
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/common/components/header/components/navigation/navigation.tsx]:
```suggestion
                        src={avatarUrl ?? defaultAvatar}
```

Comment (anton-otroshchenko) [reply frontend/src/bundles/common/components/header/components/navigation/navigation.tsx]: https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md

A1

**Review by anton-otroshchenko — DISMISSED** [review]

**Review by nikita-remeslov — APPROVED** [review]
