### PR TITLE
LIME-519: Fix relation issue

### LINKED ISSUE #519: Fix issues with relations

### PR DESCRIPTION
**Pull request by ArtemLymarenko**

### CODE REVIEW

**Review by anton-otroshchenko — DISMISSED** [review]

File: frontend/src/bundles/chats/components/chat-link/chat-link.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ const ChatLink = ({
                         <div className="relative">
                             <Avatar
                                 size="sm"
-                                email={email}
+                                email={fullName || email}
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/chats/components/chat-link/chat-link.tsx]: use nullish operator

**Review by stpalamar — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
