### PR TITLE
LIME-134: Fix avatar component

### LINKED ISSUE #134: BUG: Fix Avatar Component
- [ ] Avatar component should not use the redux state directly
- [ ] Avatar should take avatarUrl and email in props

### PR DESCRIPTION
**Pull request by DavidCharif**
image

### CODE REVIEW

File: frontend/src/bundles/common/components/avatar/avatar.tsx [hunk 1]
```diff
@@ -9,6 +8,8 @@ type AvatarSize = Exclude<
 
 type Properties = {
     size: AvatarSize;
+    email: string;
+    avatarUrl: string;
```
Comment (dimapopovych) [inline frontend/src/bundles/common/components/avatar/avatar.tsx]:
```suggestion
    avatarUrl: string | null;
```

**Review by dimapopovych — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/common/components/avatar/avatar.tsx (hunk 1 above)
Comment (DavidCharif) [reply frontend/src/bundles/common/components/avatar/avatar.tsx]: image

**Review by jhladkov — APPROVED** [review]

**Review by dimapopovych — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
