### PR TITLE
LIME-293: Fix redirecting to auth page

### LINKED ISSUE #293: BUG: Instead of loader, Sign In page is displayed for a moment to the logged in user when he tries to reach Sign in page
### Describe your issue

- [ ] Sign In page is displayed for а moment to the logged in user when he tries to reach Sign in page 
- [ ] Sign Up page is displayed for а moment to the logged in user when he tries to reach Sign up page 

### Steps to reproduce

1. Go to https://live-in-motion-everyday.com/
2. Being redirected to Sign in page, login with valid credentials
3. Try to reach Sign in page through URL https://live-in-motion-everyday.com/sign-in
4. Pay attention to the page, displayed before redirection to Home page
5. Try to reach Sign up page through URL https://live-in-motion-everyday.com/sign-up
6. Pay attention to the page, displayed before redirection to Home page

### What was the actual result?

- [ ] Sign In page is displayed for а moment to the logged in user when he tries to reach Sign in page, then user is redirected to Home page 
- [ ] Sign Up page is displayed for а moment to the logged in user when he tries to reach Sign up page, then user is redirected to Home page

### What was the expected result?

Loader is displayed for several seconds to the logged in user when he tries to reach Sign in or Sign up page, then user is redirected to Home page

### Put here any screenshots or videos (optional)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/123622110/44680a7b-a47b-45db-9435-b8860867a11b

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

### PR DESCRIPTION
**Pull request by valery-chumak**

### CODE REVIEW

**Review by ivanbilobrov07 — DISMISSED** [review]

File: frontend/src/bundles/auth/pages/auth.tsx [hunk 1]
```diff
@@ -132,6 +134,10 @@ const Auth: React.FC = () => {
             'hidden flex-1 items-center justify-center text-xl text-primary lg:flex',
     };
 
+    if (isRefreshing || user) {
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/auth/pages/auth.tsx:135]: `|| user` - is it necessary?

Comment (valery-chumak) [reply frontend/src/bundles/auth/pages/auth.tsx:135]: Yes, because without this condition it shows a sign-in page for a second after loader for authorized user

**Comment by valery-chumak** [comment]
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/72942456/4e03ca33-df7a-450d-a50c-e6a5e3f798be

**Review by nikita-remeslov — APPROVED** [review]

File: frontend/src/bundles/auth/pages/auth.tsx [hunk 2]
```diff
@@ -37,9 +38,10 @@ const Auth: React.FC = () => {
     const [isOpen, setIsOpen] = useState(false);
     const [isPasswordForgot, setIsPasswordForgot] = useState(false);
 
-    const { dataStatus, user } = useAppSelector(({ auth }) => ({
+    const { dataStatus, user, isRefreshing } = useAppSelector(({ auth }) => ({
         dataStatus: auth.dataStatus,
         user: auth.user,
+        isRefreshing: auth.isRefreshing,
     }));
```
Comment (nikita-remeslov) [inline frontend/src/bundles/auth/pages/auth.tsx]:
```suggestion
    const { dataStatus, user, isRefreshing } = useAppSelector(({ auth }) => auth);
```

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

File: frontend/src/bundles/auth/pages/auth.tsx (hunk 2 above)
Comment (valery-chumak) [reply frontend/src/bundles/auth/pages/auth.tsx]: Fixed)

**Review by dimapopovych — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
