### PR TITLE
LIME-450: Constrains to upload image file type.

### LINKED ISSUE #450: BUG: The "Crop your avatar" window is opened after user chooses the file of incorrect format when uploading the avatar
### Describe your issue

The "Crop your avatar" window is opened after user chooses the file of incorrect format when uploading the avatar

### Steps to reproduce

1. Go to [https://live-in-motion-everyday.com/profile/information](https://live-in-motion-everyday.com/profile/information)
2. Click on the "Update file" button
3. Choose the file of incorrect format(pdf for example)
4. Pay attention to the "Crop your avatar" window

### What was the actual result?

The "Crop your avatar" window is opened after user chooses the file of incorrect format when uploading the avatar

### What was the expected result?

The "Crop your avatar" window is not opened after user chooses the file of incorrect format when uploading the avatar. Display the error "Chosen file should be an image"
OR
The user does not have the opportunity to choose the file of incorrect format when uploading the avatar

### Put here any screenshots or videos (optional)

Image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by DavidCharif**
image

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/53876827/7112e41c-c2af-4d25-a2aa-b6a954c8076f

### CODE REVIEW

File: frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx [hunk 1]
```diff
@@ -53,6 +54,7 @@ const ProfileSettings: React.FC<Properties> = ({
     isLoading,
 }) => {
     const fileInputReference = useRef<HTMLInputElement>(null);
+    const [imgFileError, setImgFileError] = useState(false);
```
Comment (dimapopovych) [inline frontend/src/bundles/profile/components/profile-settings/profile-settings.tsx]: let's just show toast notification

**Review by dimapopovych — CHANGES_REQUESTED** [review]

**Review by stpalamar — APPROVED** [review]

**Review by dimapopovych — APPROVED** [review]
