### PR TITLE
LIME-463: BUG: Workout card for walking activity displays 0 km when distance > 0, steps = 0, provider null

### LINKED ISSUE #463: BUG: Workout card for walking activity displays 0 km when distance > 0, steps = 0, provider null
### Describe your issue

Workout card on Workout page displays 0 km for walking activity when value of distance is more than 0, value of steps is 0, provider null 

### Steps to reproduce

1. Log into https://live-in-motion-everyday.com/ in browser and Postman under the same valid credentials
2. Add workout in Postman with activityType = walking, distance > 0, steps = 0, provider null 
3. Navigate to the workout page, pay attention to the displayed distance of the added workout

### What was the actual result?

Workout card on Workout page displays 0 km for walking activity when value of distance is more than 0, value of steps is 0

### What was the expected result?

Workout card on Workout page displays actual distance of workout when value of steps is 0

### Put here any screenshots or videos (optional)

image

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

### PR DESCRIPTION
**Pull request by DavidCharif**
image
image

### CODE REVIEW

**Review by stpalamar — DISMISSED** [review]

File: frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx [hunk 1]
```diff
@@ -23,7 +23,8 @@ const WorkoutStats: React.FC<Properties> = ({ workout }): JSX.Element => {
         workoutEndedAt,
     } = workout;
 
-    const workoutDistance = steps ?? metersToKilometers(distance);
+    const workoutDistance =
+        steps && steps != 0 ? steps : metersToKilometers(distance);
```
Comment (anton-otroshchenko) [inline frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx]:
```suggestion
        steps && steps !== 0 ? steps : metersToKilometers(distance);
```

**Review by anton-otroshchenko — CHANGES_REQUESTED** [review]

**Review by stpalamar — APPROVED** [review]

File: frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx [hunk 2]
```diff
@@ -23,7 +23,8 @@ const WorkoutStats: React.FC<Properties> = ({ workout }): JSX.Element => {
         workoutEndedAt,
     } = workout;
 
-    const workoutDistance = steps ?? metersToKilometers(distance);
+    const workoutDistance =
+        steps && steps !== 0 ? steps : metersToKilometers(distance);
```
Comment (dimapopovych) [inline frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx:27]: `const workoutDistance = steps || metersToKilometers(distance);`

just curious, is this disallowed by linter? no need to adjust

Comment (DavidCharif) [reply frontend/src/bundles/workouts/components/workout-stats/workout-stats.tsx:27]: image
No, it is valid i just went to the direct approach without seeing that option

**Review by nikita-remeslov — APPROVED** [review]
