### PR TITLE
LIME-162: * fix user refreshing

### LINKED ISSUE #162: BUG: Registered user with stored token is redirected to the Sign In page after refreshing Home page
### Describe your issue

After Sign Up and successful obtaining of token, user is redirected to Sign In if he refreshes the Home page 

### Steps to reproduce

1. Open Sign Up page
2. Register with valid data
3. Check if token is stored in the local storage
4. Refresh home page where user was redirected after registering
5. Check if home page is displayed

### What was the actual result?

After Sign Up and successful obtaining of token, user is redirected to Sign In if he refreshes the Home page 

### What was the expected result?

Home page is displayed to the user after refreshing

### Put here any screenshots or videos (optional)

_No response_

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

### PR DESCRIPTION
**Pull request by ivanbilobrov07**

### CODE REVIEW

File: frontend/src/app/app.tsx [hunk 1]
```diff
@@ -1,56 +1,35 @@
...
+            } finally {
+                setIsRefreshing(false);
+            }
+        };
+
+        void refreshUser();
     }, [dispatch]);
 
-    if (dataStatus === DataStatus.PENDING) {
+    if (isRefreshing) {
```
Comment (nikita-remeslov) [inline frontend/src/app/app.tsx:28]: why do we need to change it?

File: frontend/src/bundles/common/components/protected-route/protected-route.tsx [hunk 2]
```diff
@@ -3,18 +3,18 @@ import { type ReactNode } from 'react';
...
 type ProtectedRouteProperties = {
     children: ReactNode;
 };
 
 const ProtectedRoute: React.FC<ProtectedRouteProperties> = ({ children }) => {
-    const userAuthenticated = useAppSelector(
-        (state: AsyncThunkConfig['state']) => state.auth.user,
-    );
+    const { isRefreshing, userAuthenticated } = useAppSelector(({ auth }) => ({
+        isRefreshing: auth.isRefreshing,
```
Comment (nikita-remeslov) [inline frontend/src/bundles/common/components/protected-route/protected-route.tsx:13]: why do we need this flag?

**Review by nikita-remeslov — CHANGES_REQUESTED** [review]

File: frontend/src/app/app.tsx (hunk 1 above)
Comment (ivanbilobrov07) [reply frontend/src/app/app.tsx:28]: https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-lime/assets/112903531/81491a16-d6cf-4d44-9378-ed0de4ff167a

Because it is used in register page for loader in button and if I add it, there would be something like that

File: frontend/src/bundles/common/components/protected-route/protected-route.tsx (hunk 2 above)
Comment (ivanbilobrov07) [reply frontend/src/bundles/common/components/protected-route/protected-route.tsx:13]: We need it not to redirect to the sign-in page while the user is refreshing

**Review by dimapopovych — APPROVED** [review]

**Review by DavidCharif — APPROVED** [review]

**Review by valery-chumak — APPROVED** [review]

**Review by stpalamar — APPROVED** [review]

**Review by nikita-remeslov — APPROVED** [review]
